import localFont from 'next/font/local';
import '@styles/globals.css';

const outfit = localFont({
  src: [
    {
      path: 'fonts/Outfit-Light.ttf',
      weight: '300',
      style: 'light',
    },
    {
      path: 'fonts/Outfit-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
  ],
  variable: '--font-outfit',
});

export const metadata = {
  title: 'Entertainment Web App',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/images/favicon-32x32.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased font-sans font-light`}>
        {children}
      </body>
    </html>
  );
}
